import time
from pages.personal_account_page import PersonalPage
from test_personal_account_page.data import LOGIN_PKG, PASSWORD_PGK, LOGIN_PKG_COORDINAT, PASSWORD_PGK_COORDINAT, \
    LOGIN_PKG_COORDINAT_2, PASSWORD_PGK_COORDINAT_2


class Test:
    def test_2(self, browser):
        test = PersonalPage(browser)
        test.open_catalog()
        time.sleep(5)
        test.login_button()
        time.sleep(2)
        test.login_input_send_keys(LOGIN_PKG)
        test.password_input_send_keys(PASSWORD_PGK)
        test.click_enter_button()
        time.sleep(2)
        test.open_products_and_services()
        time.sleep(2)
        test.click_button_create_request()
        time.sleep(10)
        test.click_button_list_positions()
        time.sleep(2)
        test.click_button_upload_file()
        time.sleep(2)
        test.get_button_upload_file()
        time.sleep(2)
        test.click_button_send_approval()
        time.sleep(5)
        test.click_button_send()
        time.sleep(7)
        url_application = test.save_url_application()
        application = url_application[-7:]
        print(application)
        test.click_button_output_lk()
        time.sleep(10)
        test.login_input_send_keys(LOGIN_PKG_COORDINAT)
        test.password_input_send_keys(PASSWORD_PGK_COORDINAT)
        test.click_enter_button()
        time.sleep(3)
        test.open(url_application)
        time.sleep(20)
        test.click_button_approval()
        time.sleep(3)
        test.click_button_approval_form()
        time.sleep(10)
        test.click_button_output_lk()
        time.sleep(10)
        test.login_input_send_keys(LOGIN_PKG_COORDINAT_2)
        test.password_input_send_keys(PASSWORD_PGK_COORDINAT_2)
        test.click_enter_button()
        time.sleep(3)
        test.open(url_application)
        time.sleep(20)
        test.click_button_approval()
        time.sleep(3)
        test.click_button_approval_form()
        time.sleep(3)
