import time
import allure
from pages.personal_account_page import PersonalPage
from pages.requirements_page import RequirementsPage
from create_application_page.data import LOGIN_PKG, PASSWORD_PGK, LOGIN_PKG_COORDINAT, PASSWORD_PGK_COORDINAT, \
    LOGIN_PKG_COORDINAT_2, PASSWORD_PGK_COORDINAT_2


class TestCreatingApplication:
    @allure.title("Создание заявки с согласованием, сценарий 1.2")
    def test_creating_application(self, browser):
        personal = PersonalPage(browser)
        requirements = RequirementsPage(browser)
        personal.open_catalog()
        time.sleep(5)
        personal.login_button()
        time.sleep(2)
        personal.login_input_send_keys(LOGIN_PKG)
        personal.password_input_send_keys(PASSWORD_PGK)
        personal.click_enter_button()
        time.sleep(2)
        personal.open_products_and_services()
        time.sleep(5)
        personal.click_button_create_request()
        time.sleep(10)
        personal.click_button_list_positions()
        time.sleep(2)
        personal.click_button_upload_file()
        time.sleep(2)
        personal.get_button_upload_file()
        time.sleep(2)
        personal.click_button_send_approval()
        time.sleep(5)
        personal.click_button_send()
        time.sleep(7)
        url_application = personal.save_url_application()
        application = url_application.split('/')[-2].strip('/')
        personal.click_button_output_lk()
        time.sleep(10)
        personal.login_input_send_keys(LOGIN_PKG_COORDINAT)
        personal.password_input_send_keys(PASSWORD_PGK_COORDINAT)
        personal.click_enter_button()
        time.sleep(3)
        personal.open(url_application)
        time.sleep(7)
        personal.click_button_approval()
        time.sleep(3)
        personal.click_button_approval_form()
        time.sleep(3)
        personal.click_button_output_lk()
        time.sleep(7)
        personal.login_input_send_keys(LOGIN_PKG_COORDINAT_2)
        personal.password_input_send_keys(PASSWORD_PGK_COORDINAT_2)
        personal.click_enter_button()
        time.sleep(3)
        personal.open(url_application)
        time.sleep(7)
        personal.click_button_approval()
        time.sleep(3)
        personal.click_button_approval_form()
        time.sleep(3)
        personal.click_button_output_lk()
        time.sleep(10)
        personal.login_input_send_keys(LOGIN_PKG)
        personal.password_input_send_keys(PASSWORD_PGK)
        personal.click_enter_button()
        time.sleep(2)
        personal.open_personal_requirements()
        time.sleep(10)
        numbers = requirements.get_number_application()
        time.sleep(10)
        if application == numbers:
            print(numbers)
        else:
            print('Не прокатило не фартануло')
