LOGIN_PKG = 'andrei.arutyunov'
PASSWORD_PGK = 'Andrei.arutyunov_123'

SEND_MIGRATION = '''<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="urn:ws">
        <SOAP-ENV:Body>
                <RemoteContract.setMigratedDocument xmlns="">
                        <auth>
                                <login>andrei.arutyunov</login>
                                <password>Andrei.arutyunov_123</password>
                        </auth>
                        <documents>
                                <document>
                                        <contract_external_id>1928</contract_external_id>
                                        <parent_contract_external_id></parent_contract_external_id>
                                        <case_title>Тра-та-та</case_title>
                                        <auto_renewal_category_code>R</auto_renewal_category_code>
                                        <currency_code>RUB</currency_code>
                                        <rcm_sum_with_nds>12.00</rcm_sum_with_nds>
                                        <validity_start_date>2024-11-15</validity_start_date>
                                        <validity_end_date>2024-11-16</validity_end_date>
                                        <vat_rate>10</vat_rate>
                                        <rcm_sign_place>Москва, Ленина, 24</rcm_sign_place>
                                        <payment_condition>A500</payment_condition>
                                        <contract_state_code>5</contract_state_code>
                                        <payment_currency_code>RUB</payment_currency_code>
                                        <rcm_sum_no_nds>10</rcm_sum_no_nds>
                                        <contract_manager>manager@mail.ru</contract_manager>
                                        <business_partner_number>123123123</business_partner_number>
										<contract_kind_code>R</contract_kind_code>
                                        <positions>
                                                <position>
                                                        <item_number>1406005</item_number>
                                                        <material_number>1000000670</material_number>
                                                        <unit_of_measure>12301</unit_of_measure>
                                                        <quantity>11</quantity>
                                                        <net_amount>5.50</net_amount>
                                                        <purchase_plant>1050</purchase_plant>
                                                        <warehouse>2134</warehouse>
                                                        <purchasing_group>131</purchasing_group>
                                                </position>
                                                <position>
                                                        <item_number>1406006</item_number>
                                                        <material_number>1000000670</material_number>
                                                        <unit_of_measure>765</unit_of_measure>
                                                        <quantity>3</quantity>
                                                        <net_amount>10.50</net_amount>
                                                        <purchase_plant>1050</purchase_plant>
                                                        <warehouse>2134</warehouse>
                                                        <purchasing_group>131</purchasing_group>
                                                </position>
                                        </positions>
									<additional_fields_values>
                                                <field_value>
                                                        <type>string</type>
                                                        <sys_name>document_type</sys_name>
                                                        <string_value>
                                                                <value>D</value>
                                                        </string_value>
                                                </field_value>
												<field_value>
                                                        <type>string</type>
                                                        <sys_name>rcm_fipex</sys_name>
                                                        <string_value>
                                                                <value>1.2.1.0</value>
                                                        </string_value>
                                                </field_value>
												<field_value>
                                                        <type>string</type>
                                                        <sys_name>rcm_type_summ</sys_name>
                                                        <string_value>
                                                                <value>N</value>
                                                        </string_value>
                                                </field_value>
												<field_value>
                                                        <type>string</type>
                                                        <sys_name>contract_category_code</sys_name>
                                                        <string_value>
                                                                <value>PDPD</value>
                                                        </string_value>
                                                </field_value>
												<field_value>
                                                        <type>string</type>
                                                        <sys_name>rcm_sub_categ</sys_name>
                                                        <string_value>
                                                                <value>ZPRZ</value>
                                                        </string_value>
                                                </field_value>
												<field_value>
                                                        <type>string</type>
                                                        <sys_name>business_area_code</sys_name>
                                                        <string_value>
                                                                <value>1001</value>
                                                        </string_value>
                                                </field_value>
												<field_value>
                                                        <type>string</type>
                                                        <sys_name>financial_management_position</sys_name>
                                                        <string_value>
                                                                <value>100100000</value>
                                                        </string_value>
                                                </field_value>
												<field_value>
                                                        <type>string</type>
                                                        <sys_name>activity_category</sys_name>
                                                        <string_value>
                                                                <value>10100001</value>
                                                        </string_value>
                                                </field_value>
												<field_value>
                                                        <type>boolean</type>
                                                        <sys_name>rcm_subs_id</sys_name>
                                                        <bool_value>
                                                                <value>true</value>
                                                        </bool_value>
                                                </field_value>
												<field_value>
                                                        <type>string</type>
                                                        <sys_name>house_bank</sys_name>
                                                        <string_value>
                                                                <value>ALF01</value>
                                                        </string_value>
                                                </field_value>
												<field_value>
                                                        <type>string</type>
                                                        <sys_name>account_details_id</sys_name>
                                                        <string_value>
                                                                <value>RP239</value>
                                                        </string_value>
                                                </field_value>
												<field_value>
                                                        <type>string</type>
                                                        <sys_name>rcm_act_period</sys_name>
                                                        <string_value>
                                                                <value>4</value>
                                                        </string_value>
                                                </field_value>
												<field_value>
														<type>boolean</type>
														<sys_name>load_catalog</sys_name>
														<bool_value>
																<value>true</value>
														</bool_value>
														</field_value>
                                        </additional_fields_values>
                                </document>
                        </documents>
                </RemoteContract.setMigratedDocument>
        </SOAP-ENV:Body>
</SOAP-ENV:Envelope>'''
